FILE       = function.cpp 
EXECUTABLE = function 
XLIBS      = -L/usr/X11R6/lib -lglut -lGLU -lGL 
GLLIBS     = -lglut -lGLU -lGL
CC         = clang++

default: $(FILE)
	$(CC) $(FILE) $(XLIBS) $(GLLIBS)  -o $(EXECUTABLE) 
