FILE       = arches.cpp 
EXECUTABLE = arches
XLIBS      = -L/usr/X11R6/lib -lglut -lGLU -lGL 
GLLIBS     = -lglut -lGLU -lGL
CC         = g++ -Wall -std=c++11

default: $(FILE)
	$(CC) $(FILE) $(XLIBS) $(GLLIBS)  -o $(EXECUTABLE) 
